//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itcast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int MsgId { get; set; }
        public Nullable<int> SendId { get; set; }
        public Nullable<int> ReceiveId { get; set; }
        public string MsgTxt { get; set; }
        public System.DateTime MsgSendTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
